[package]
name = "zrush_panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zrush_panel.rs"
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
settings.workspace = true
task.workspace = true
terminal_view.workspace = true
ui.workspace = true
workspace.workspace = true
zed_actions.workspace = true
zrush-core = { git = "https://github.com/christphe/zrush", rev = "e90d16dd5f102d59b936a7b990e0fea0948b0c73" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
