[package]
name = "zrush_panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zrush_panel.rs"
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
ui.workspace = true
workspace.workspace = true
zed_actions.workspace = true
zrush-core = { git = "https://github.com/christphe/zrush", rev = "4c3a37637b6d6fd8c3e01988a1d58489faa33d4d" }
